include: package:ubuntu_lints/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/l10n/*.dart"

linter:
  rules:
    avoid_print: true
    directives_ordering: false # I prefer grouped directive ordering
