name: tomypod
description: 'A pipeline app to transfer local data to PODs.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  solid:
    path: solid # Use a local path whilst solid is under development.
    ## git:
    ##   url: https://github.com/anusii/solid
    ##   ref: main
  universal_io: ^2.2.2
  window_manager: ^0.3.7

dev_dependencies:
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: main
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.jpg
    - assets/images/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
